<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <RootNamespace>Talaryon.WebKit</RootNamespace>
        <AssemblyName>Talaryon.WebKit</AssemblyName>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    
    <ItemGroup>
      <Compile Update="Components\WebKitGridViewItem.cs">
        <DependentUpon>WebKitGridView.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\WebKitBreadcrumbItem.cs">
        <DependentUpon>WebKitBreadcrumbs.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\IWebKitGalleryItem.cs">
        <DependentUpon>WebKitGallery.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\WebKitPriceViewItem.cs">
        <DependentUpon>WebKitPriceView.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\WebKitPriceViewLabels.cs">
        <DependentUpon>WebKitPriceView.razor</DependentUpon>
      </Compile>
    </ItemGroup>
    
    <ItemGroup>
      <UpToDateCheckInput Remove="Components\Blog\WebKitBlog.razor" />
      <UpToDateCheckInput Remove="Components\Blog\WebKitBlogPost.razor" />
    </ItemGroup>
    
    <ItemGroup>
      <Content Remove="Components\WebKitNavBar2.razor" />
      <None Include="Components\WebKitNavBar2.razor" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.2" />
      <PackageReference Include="talaryon.toolbox" Version="1.0.0" />
    </ItemGroup>


</Project>
