<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <RootNamespace>Talaryon.WebKit</RootNamespace>
        <AssemblyName>Talaryon.WebKit</AssemblyName>
        <LangVersion>14</LangVersion>
        <Title>Talaryon WebKit</Title>
        <Authors>Talaryon Labs</Authors>
        <Copyright>Talaryon Labs</Copyright>
        <PackageProjectUrl>https://github.com/talaryonlabs/webkit</PackageProjectUrl>
        <RepositoryUrl>https://github.com/talaryonlabs/webkit</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Company>Talaryon Labs</Company>
        <Product>Talaryon WebKit</Product>
        <AssemblyVersion>1.0.1</AssemblyVersion>
        <IsPackable>true</IsPackable>
        <Version>1.0.1</Version>
        <PackageId>Talaryon.WebKit</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    
    <ItemGroup>
      <Compile Update="Components\WebKitGridViewItem.cs">
        <DependentUpon>WebKitGridView.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\WebKitBreadcrumbItem.cs">
        <DependentUpon>WebKitBreadcrumbs.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\IWebKitGalleryItem.cs">
        <DependentUpon>WebKitGallery.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\WebKitPriceViewItem.cs">
        <DependentUpon>WebKitPriceView.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\WebKitPriceViewLabels.cs">
        <DependentUpon>WebKitPriceView.razor</DependentUpon>
      </Compile>
    </ItemGroup>
    
    <ItemGroup>
      <UpToDateCheckInput Remove="Components\Blog\WebKitBlog.razor" />
      <UpToDateCheckInput Remove="Components\Blog\WebKitBlogPost.razor" />
    </ItemGroup>
    
    <ItemGroup>
      <Content Remove="Components\WebKitNavBar2.razor" />
      <None Include="Components\WebKitNavBar2.razor" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.2" />
      <PackageReference Include="Talaryon.Toolbox" Version="1.3.6" />
      <PackageReference Include="Talaryon.Toolbox.Services" Version="1.0.2" />
    </ItemGroup>


</Project>
